name: deploy

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.actor }}"
  deploy:
    needs: start
    environment: 
      name: prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to production"
  monitor-deploy:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Work
        run: |
          for i in {1..6}; do
            echo ${{ toJson( github ) }}
            sleep 1
          done

      - name: Check for pending deployments
        id: check
        run: |
          pending_jobs=$(gh api -X GET /repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.conclusion == null and .name == "deploy") | .id')
          echo "pending_jobs=$pending_jobs" >> $GITHUB_ENV
