name: deploy

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.actor }}"
  deploy:
    needs: start
    environment: 
      name: prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to production"
  monitor-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Work
        run: echo "Working"