name: deploy

on:
  push:
    branches:
      - main

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.actor }}"
  deploy:
    needs: test-actions
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to production"