name: CI

on: push

jobs:
  # test-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Use sds9/action-sandbox@main
  #       uses: sds9/action-sandbox@main
  #       with:
  #         example-input: 'World'

  #     - name: Use sds9/action-sandbox/utils@main
  #       uses: sds9/action-sandbox/utils@main
  #       with:
  #         example-input: 'GitHub'


  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo GitHub event
        run: echo '${{ toJson(github) }}' | jq .

      - name: Check changed files
        id: changed-files
        run: echo ::set-output name=files::$(git diff --name-only main...${{ github.ref_name }})

      - name: Check Docker image changes
        id: docker-changed
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Dockerfile')
          if [ -n "$changed_files" ]; then
            echo "::set-output name=changed::Dockerfile"
          else
            echo "::set-output name=changed::"
          fi

      - name: Build Docker image
        run: docker build -t my-docker-image .
        if: steps.docker-changed.outputs.changed == 'Dockerfile'