name: variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_NUMBER: ${{ github.event.inputs.environment == 'dev' && '123456789012' || '210987654321' }}
      REGION: ${{ github.event.inputs.environment == 'dev' && 'us-west-2' || 'us-east-1' }}
      BUCKET: ${{ github.event.inputs.environment == 'dev' && 'my-dev-bucket' || 'my-prod-bucket' }}
    steps:
      - name: Display environment variables
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Account number: $ACCOUNT_NUMBER"
          echo "Region: $REGION"
          echo "Bucket: $BUCKET"

      - name: Example step using environment variables
        run: |
          echo "Deploying to account $ACCOUNT_NUMBER in region $REGION using bucket $BUCKET"
