name: variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  dev_account_number: 123456789012
  prod_account_number: 210987654321
  dev_region: us-west-2
  prod_region: us-east-1
  dev_bucket: my-dev-bucket
  prod_bucket: my-prod-bucket

jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    steps:
      - name: Set environment variables
        run: |
          if [ "${{ matrix.environment }}" == "dev" ]; then
            echo "ACCOUNT_NUMBER=123456789012" >> $GITHUB_ENV
            echo "REGION=us-west-2" >> $GITHUB_ENV
            echo "BUCKET=my-dev-bucket" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" == "prod" ]; then
            echo "ACCOUNT_NUMBER=210987654321" >> $GITHUB_ENV
            echo "REGION=us-east-1" >> $GITHUB_ENV
            echo "BUCKET=my-prod-bucket" >> $GITHUB_ENV
          fi

      - name: Display environment variables
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Account number: $ACCOUNT_NUMBER"
          echo "Region: $REGION"
          echo "Bucket: $BUCKET"
