name: variables

on:
  push:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set and use multiline output in the same step
        id: set-and-use-multiline-output
        run: |
          multiline_output=$(cat <<EOF
          Line 1
          Line 2
          Line 3
          EOF
          )
          echo "multiline-output<<EOF" >> $GITHUB_OUTPUT
          echo "$multiline_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "Multiline output:"
          echo "$multiline_output"

      - name: Use multiline output
        run: |
          echo "Multiline output:"
          echo "${{ steps.set-and-use-multiline-output.outputs.multiline-output }}"
