name: variables

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Environment to deploy to'
  #       required: true
  #       type: choice
  #       options:
  #         - dev
  #         - test
  #         - prod

# env:
#   ACCOUNT_NUMBER: ${{ inputs.environment == 'dev' && '123456789012' || inputs.environment == 'test' && '111111111111' || '210987654321' }}
#   REGION: ${{ inputs.environment == 'dev' && 'us-west-2' || inputs.environment == 'test' && 'us-central-1' || 'us-east-1' }}
#   BUCKET: ${{ inputs.environment == 'dev' && 'my-dev-bucket' || inputs.environment == 'test' && 'my-test-bucket' || 'my-prod-bucket' }}

jobs:
  # start:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Display environment variables
  #       run: |
  #         echo "Environment: ${{ inputs.environment }}"
  #         echo "Account number: $ACCOUNT_NUMBER"
  #         echo "Region: $REGION"
  #         echo "Bucket: $BUCKET"

  #     - name: Example step using environment variables
  #       run: |
  #         echo "Deploying to account $ACCOUNT_NUMBER in region $REGION using bucket $BUCKET"
      

  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set and use multiline output in the same step
        id: set-and-use-multiline-output
        run: |
          multiline_output=$(cat <<EOF
          Line 1
          Line 2
          Line 3
          EOF
          )
          echo "multiline-output<<EOF" >> $GITHUB_OUTPUT
          echo "$multiline_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "Multiline output:"
          echo "$multiline_output"

      - name: Use multiline output
        run: |
          echo "Multiline output:"
          echo ${{ steps.set-and-use-multiline-output.outputs.multiline-output }}